### ISSUE TITLE
Fix Pipfile's Python Version Python 3.7

### ISSUE THREAD

**Issue by Xevion** [n0remac/2020GameJamPractice#4]
On installation, the `dataclasses` module will not be available as it's not a part of the Python 3.6 Standard Library. Python 3.7 does. We should change the version to 3.7 in order to remedy this.

```
C:\Users\Xevion\.virtualenvs\2020GameJamPractice-3ncM_Ykx\Scripts\python.exe F:/Programming/Python/Arcade/2020GameJamPractice/platformer.py
Traceback (most recent call last):
  File "C:\Users\Xevion\.virtualenvs\2020GameJamPractice-3ncM_Ykx\lib\site-packages\arcade\sprite.py", line 10, in <module>
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/Programming/Python/Arcade/2020GameJamPractice/platformer.py", line 4, in <module>
    import arcade
  File "C:\Users\Xevion\.virtualenvs\2020GameJamPractice-3ncM_Ykx\lib\site-packages\arcade\__init__.py", line 167, in <module>
    from .emitter import EmitBurst
  File "C:\Users\Xevion\.virtualenvs\2020GameJamPractice-3ncM_Ykx\lib\site-packages\arcade\emitter.py", line 7, in <module>
    from arcade.particle import Particle
  File "C:\Users\Xevion\.virtualenvs\2020GameJamPractice-3ncM_Ykx\lib\site-packages\arcade\particle.py", line 5, in <module>
    from arcade.sprite import Sprite
  File "C:\Users\Xevion\.virtualenvs\2020GameJamPractice-3ncM_Ykx\lib\site-packages\arcade\sprite.py", line 12, in <module>
    raise Exception('dataclasses not available, if running on Python 3.6 please manually install '
Exception: dataclasses not available, if running on Python 3.6 please manually install https://pypi.org/project/dataclasses/

Process finished with exit code 1
```

[Referenced Line in Pipfile](https://github.com/n0remac/2020GameJamPractice/blob/fa53ecacb0736e87097722f8297e036f86e96e28/Pipfile#L12)

**Comment by n0remac** [comment]
I think there is probably a way to do this with pipenv, but I couldn't find it. I am going to try and just change it manually in the Pipfile.
